version: '3.8'

services:
  app:
    build: .
    container_name: data_flow_pipeline
    depends_on:
      db:
        condition: service_healthy  # Waits for DB to be ready
    environment:
      - DB_HOST=mysql_db
      - DB_NAME=mainstreet_data_pipeline
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    volumes:
      - .:/app
    networks:
      - data_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mainstreet_data_pipeline
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - data_network
    healthcheck:  # <== Added this
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  mysql_data:

networks:
  data_network:
    driver: bridge
